-- Borra las tablas si existen (en orden inverso a las dependencias)
drop table if exists ENTRADAS;
drop table if exists USER_ROLES;
drop table if exists USUARIOS;
drop table if exists PELICULAS;

-- Crea la tabla PELICULAS
create table PELICULAS (
    id_pelicula bigint generated by default as identity PRIMARY KEY,
    titulo varchar(255) not null,
    genero varchar(255) not null,
    duracion integer not null,
    sinopsis varchar(255),
    actores_principales varchar(255),
    actores_secundarios varchar(255),
    director varchar(255) not null,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

-- Crea la tabla USUARIOS
create table USUARIOS (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(255) not null,
    apellidos varchar(255) not null,
    username varchar(255) not null unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

-- Crea la tabla USER_ROLES
create table USER_ROLES (
    user_id bigint not null,
    roles varchar(10) not null check (roles in ('ADMIN','USER'))
);

-- Crea la tabla ENTRADAS
create table ENTRADAS (
    id_entrada bigint generated by default as identity PRIMARY KEY,
    fecha date not null,
    precio float(53) not null,
    metodo_pago varchar(255) not null,
    pelicula_id bigint not null,
    usuario_id bigint,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

-- Añade las claves foráneas
alter table if exists ENTRADAS
    add constraint fk_entradas_peliculas_pelicula_id 
    foreign key (pelicula_id) 
    references PELICULAS(id_pelicula);

alter table if exists ENTRADAS
    add constraint fk_entradas_usuarios_usuario_id 
    foreign key (usuario_id) 
    references USUARIOS(id);

alter table if exists USER_ROLES
    add constraint fk_user_roles_usuarios_user_id 
    foreign key (user_id) 
    references USUARIOS(id);
